### ISSUE TITLE
Doesn't pull up an OS X dialog box to prompt for password

### ISSUE THREAD

**Issue by erikmellum** [jorangreef/sudo#2]
I can't seem to get this to pull up a dialog box even in the simplest of cases. If I try the following:

```
sudo.exec('touch /etc/test.txt', function(err){if(err)console.log(err)})
```
It will silently fail with no prompt, and nothing on the errors object.

I did notice one thing that may be relevant.

If I attempt the command in the console window `sudo touch /etc/test.txt` then I get a prompt to enter the password. After I have entered the password using the command window, the programmatic version begins to work with sudo commands (but will never properly prompt for a password). I would really like to figure out why this isn't working and was wondering if you had any debug suggestions. 

I've also tried mixing `sudo.touch` in various locations without success. 

Thanks!

**Comment by jorangreef** [comment]
Thanks, I tried your example on OS X 10.10.4 and it worked fine.

Could the password prompt possibly be hidden by other windows?

Once you enter your password the first time using the prompt, or via a sudo command in the console, your user will have sudo privileges for a few minutes, which is why the programmatic version would not require a password prompt the second time.

It is designed to only prompt if sudo privileges are necessary, so it may look like it is silently failing by not showing a prompt each time, but it might actually be working fine.

Are you removing the `/etc/test.txt` file each time before you test, and what is the title of your process?

**Comment by erikmellum** [comment]
Thanks Joran for your response it is much appreciated. I checked and didn't locate the password prompt behind any other windows. My process.title is "/Users/guest/Desktop/yeti-launch/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper"

My process was to launch the application (with no sudo timestamp). Before I attempted the sudo command, I checked in an external terminal that /etc/test.txt did not exist using `stat '/etc/test.txt'`. After executing the sudo code, the prompt for sudo did not pop up, and the file did not exist using the same check in the external terminal `stat '/etc/test.txt'`. However, when I have a sudo timestamp available (by running anything that requires sudo in the external terminal, and entering the password), sudo execute will be able to create the `/etc/test.txt` file (albeit with no dialog prompt). I have been careful to ensure that the file does not already exist in doing these tests. It appears to be having some sort of issue pulling up the dialog box.

Hope that helps, I will continue testing for now!

**Comment by jorangreef** [comment]
Could you try and run `sudo.setName('test')` before you call `sudo.exec`?

If you could also please let me know the following:

1. What does `os.tmpdir()` return when called from your Electron app and is that path is writable by your user?

2. What does `process.env['USER']` contain when checked from your Electron app?

3. What do you get when running `which osascript` in the terminal?

4. What version of OS X are you running?

5. Are you sure that you are checking for errors when calling sudo.exec?

**Comment by erikmellum** [comment]
Running `sudo.setName('test')` fixed the issue. I told myself that the title couldn't possibly be the problem in my debugging, which was quite shortsighted. I should have tested that myself. Thanks for your assistance with my issue. The package is quite useful in my electron application.

**Comment by jorangreef** [comment]
That's great to hear.

sudo-prompt works without native dependencies by creating a copy of the osascript binary using the title of your process as the binary name. It does this so that the password prompt shows as being from your application.

I think the reason your process.title didn't work is because it contained slashes which are not valid in a pathname. sudo-prompt should definitely have given you an error in the callback if your process title was invalid:

```
[Error: Please use sudo.setName(string) to set your app name (process.title contains invalid characters).]
```
